AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaZipFunction:
    # This resource creates a Lambda function.
    Type: AWS::Serverless::Function
    Properties:
      
      # This function uses the Nodejs v6.10 runtime.
      Runtime: ruby2.5
        
      # This is the Lambda function's handler.
      Handler: lambda_function.lambda_handler
      
      # The location of the Lambda function code.
      # CodeUri: s3://lambda.ruby/lambda.zip
      CodeUri: .

      # Environment:
      #  Variables:
      #    AWS_ACCESS_KEY_ID: AKIAJ73CMXF3YS7UUDBQ
      #    AWS_SECRET_ACCESS_KEY: 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
      
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:
        LambdaZipApi:
            # Define an API Gateway endpoint that responds to HTTP GET at /thumbnail
            Type: Api
            Properties:
                Path: /lambda-zip/{zipCode}
                Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaZipFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lambda-zip"
  LambdaZipFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaZipFunction.Arn
  LambdaZipFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaZipFunctionRole.Arn
