AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaZipFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: ruby2.5
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Events:
        LambdaZipApi:
            Type: Api
            Properties:
                Path: /lambda-zip/{zipCode}
                Method: get
Outputs:
  LambdaZipFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lambda-zip"
  LambdaZipFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaZipFunction.Arn
  LambdaZipFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaZipFunctionRole.Arn
